# Generated by Django 5.2.5 on 2025-08-21 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ['-posted_at']},
        ),
    ]
