# Generated by Django 5.2.5 on 2025-08-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0002_alter_gig_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gig',
            options={'ordering': ('-posted_at',)},
        ),
        migrations.AlterField(
            model_name='gig',
            name='company',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gig',
            name='location',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gig',
            name='posted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='gig',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['title'], name='gigs_gig_title_2a53f7_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['company'], name='gigs_gig_company_2c6fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='gig',
            index=models.Index(fields=['location'], name='gigs_gig_locatio_a66831_idx'),
        ),
    ]
